### ISSUE TITLE
Hacer que los archivos se levanten de un .properties

### ISSUE THREAD

**Issue by seebogado** [AnalisisDeSoftware2017/producto_analisis_soft_2017#2]
Dejarlo en un hashmap con una clave y configurar los services para que lo puedan levantar

**Comment by matiascirojimenez** [comment]
Esta hecho esto???

**Comment by bogados-zz** [comment]
Si ya está hecho, tiene tanto como para internacionalización, además de que levanta todo de un properties.

Buscás dentro de mi branch el message.properties o algo similar (Puede ser algo como message_en_US.properties)
y el application.properties contiene las propiedades con las que se levanta el proyecto
